### ISSUE TITLE
昨天下午自动同步以后，云函数触发器突然全都没有了，没有动过环境变量

### ISSUE THREAD

**Issue by yuexx94** [asd920/Auto-jd#15]

**Comment by djhao02** [comment]
+1

**Comment by zxdc0123** [comment]
+1

**Comment by LHunique** [comment]
俺今天也没反应

**Comment by lqc206** [comment]
我也是今天没反应,求助大佬

**Comment by AN-535** [comment]
![image](https://user-images.githubusercontent.com/33016525/123045433-8088d500-d42d-11eb-9645-2f8b16f8fcb6.png)
serverless.yml这个文件，前面删掉两个空格

**Comment by AN-535** [comment]
但是下次再自动同步后还是会出问题

**Comment by asd920** [comment]
已修复

**Comment by AN-535** [comment]
> 已修复

另外，建议把内存从64调整到128，有次运行出错了，达到最大内存了
![image](https://user-images.githubusercontent.com/33016525/123047048-65b76000-d42f-11eb-9a8a-e000a88e7989.png)

**Comment by asd920** [comment]
> 
> 
> > 已修复
> 
> 另外，建议把内存从64调整到128，有次运行出错了，达到最大内存了
> ![image](https://user-images.githubusercontent.com/33016525/123047048-65b76000-d42f-11eb-9a8a-e000a88e7989.png)

加了个内存环境变量，你想内存高点的话就填下环境变量

**Comment by AN-535** [comment]
> > > 已修复
> > 
> > 
> > 另外，建议把内存从64调整到128，有次运行出错了，达到最大内存了
> > ![image](https://user-images.githubusercontent.com/33016525/123047048-65b76000-d42f-11eb-9a8a-e000a88e7989.png)
> 
> 加了个内存环境变量，你想内存高点的话就填下环境变量

内存参数设置了无效

**Comment by asd920** [comment]
> > > > 已修复
> > > 
> > > 
> > > 另外，建议把内存从64调整到128，有次运行出错了，达到最大内存了
> > > ![image](https://user-images.githubusercontent.com/33016525/123047048-65b76000-d42f-11eb-9a8a-e000a88e7989.png)
> > 
> > 
> > 加了个内存环境变量，你想内存高点的话就填下环境变量
> 
> 内存参数设置了无效

变量名称是这个 TENCENT_MemorySize
