### ISSUE TITLE
pushplus推送问题

### ISSUE THREAD

**Issue by Stars-fireworks** [asd920/Auto-jd#36]
目前在GitHub中检索到两个pushplus项目，

分别是  https://github.com/guojingyinan219/pushplus  和  https://github.com/wubin2/pushplus

不知道是正版和盗版，还是只是备份一下，但是两个项目对应的公众号不一样，token也不通用。

本项目的[环境变量说明](https://github.com/asd920/Auto-jd/blob/main/githubAction.md#%E6%8E%A8%E9%80%81%E9%80%9A%E7%9F%A5%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E7%9B%AE%E5%89%8D%E6%8F%90%E4%BE%9B%E5%BE%AE%E4%BF%A1server%E9%85%B1pushplus%E6%8E%A8%E9%80%81%E5%8A%A0ios-bark-apptelegram%E6%9C%BA%E5%99%A8%E4%BA%BA%E9%92%89%E9%92%89%E6%9C%BA%E5%99%A8%E4%BA%BA%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E6%9C%BA%E5%99%A8%E4%BA%BAigot%E7%AD%89%E9%80%9A%E7%9F%A5%E6%96%B9%E5%BC%8F)中，在**pushplus推送**一栏有对应该的[官网](http://pushplus.hxtrip.com/)，但是从该超链获取的token，使用中报错：无效的用户token。

然后去检索到的另外一个[pushplus网站](https://www.pushplus.plus/)，获取token，无报错，正常推送。

希望大佬看看 要统一成哪个项目比较合适。

**Comment by Stars-fireworks** [comment]
> > 现在在GitHub中检索到两个pushplus项目，
> > 分别是https://github.com/guojingyinan219/pushplus和https://github.com/wubin2/pushplus
> > 不知道是正版和盗版，还是只是备份一下，但是两个项目对应的公众号不一样，象征也不通用。
> > 本项目的[环境变量说明](https://github.com/asd920/Auto-jd/blob/main/githubAction.md#%E6%8E%A8%E9%80%81%E9%80%9A%E7%9F%A5%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E7%9B%AE%E5%89%8D%E6%8F%90%E4%BE%9B%E5%BE%AE%E4%BF%A1server%E9%85%B1pushplus%E6%8E%A8%E9%80%81%E5%8A%A0ios-bark-apptelegram%E6%9C%BA%E5%99%A8%E4%BA%BA%E9%92%89%E9%92%89%E6%9C%BA%E5%99%A8%E4%BA%BA%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E6%9C%BA%E5%99%A8%E4%BA%BAigot%E7%AD%89%E9%80%9A%E7%9F%A5%E6%96%B9%E5%BC%8F)中，在**pushplus的**一栏有对应该的[网](http://pushplus.hxtrip.com/)，但是从该超链获取的token，使用中报错：invalid的用户token。
> > 然后去[检索](https://www.pushplus.plus/)到的[另一个pushplus网站](https://www.pushplus.plus/)，无报错，正常获取。
> > 希望大佬要看看统一成哪个项目比较合适。
> 
> 个人觉得是第二个项目合适，只要功能能实现就行了

**Comment by Stars-fireworks** [comment]
这样。。  那还是希望修改一下，环境变量合集那里的官网超链吧。

我懵逼了好一会   才不小心搜到另一个官网。。。

**Comment by asd920** [comment]
> 这样。。 那还是希望修改一下，环境变量合集那里的官网超链吧。
> 
> 我懵逼了好一会 才不小心搜到另一个官网。。。

谢谢提醒
