### ISSUE TITLE
请问elecV2P部署的怎么进行TG bot推送？

### ISSUE THREAD

**Issue by hzx8848** [asd920/Auto-jd#41]
我在面板JS Manage 里已经添加了TG_BOT_TOKEN 和TG_USER_ID环境变量，但还是无法收到TG bot 通知，是否还要在面板设置里添加自定义通知？如果需要的话是怎么配置的呢？

**Comment by asd920** [comment]
> 我在面板JS Manage 里已经添加了TG_BOT_TOKEN 和TG_USER_ID环境变量，但还是无法收到TG bot 通知，是否还要在面板设置里添加自定义通知？如果需要的话是怎么配置的呢？

这些官方文档应该都有写，可以详细看下，再尝试配置下

**Comment by hzx8848** [comment]
已经解决，感谢！
