### ISSUE TITLE
京喜工厂 运行报错，青龙面板

### ISSUE THREAD

**Issue by 82kg** [asd920/Auto-jd#42]
开始获取京喜工厂配置文件

(node:21852) UnhandledPromiseRejectionWarning: Error: Cannot find module './jdDreamFactoryShareCodes.js'
Require stack:
- /ql/scripts/asd920_Auto-jd_jd_dreamFactory.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)

**Comment by asd920** [comment]
你应该没拉到这个文件或者拉出来不是这个文件名字，我更新下拉库命令，你再重新拉下库

**Comment by 82kg** [comment]
> 你应该没拉到这个文件或者拉出来不是这个文件名字，我更新下拉库命令，你再重新拉下库

好了，几个ShareCodes的都能拉到了。谢谢
