### ISSUE TITLE
请问这个问题如何解决？

### ISSUE THREAD

**Issue by dafeida** [asd920/Auto-jd#46]
## 开始执行... 2021-08-28 08:19:20

🔔宠汪汪, 开始!
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './JDJRValidator_Pure'
Require stack:
- /ql/scripts/asd920_Auto-jd_jd_joy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/asd920_Auto-jd_jd_joy.js:29:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/asd920_Auto-jd_jd_joy.js' ]
}

## 执行结束... 2021-08-28 08:19:20 耗时 0 秒

**Comment by asd920** [comment]
> ## 开始执行... 2021-08-28 08:19:20
> 🔔宠汪汪, 开始!
> internal/modules/cjs/loader.js:892
> throw err;
> ^
> 
> Error: Cannot find module './JDJRValidator_Pure'
> Require stack:
> 
> * /ql/scripts/asd920_Auto-jd_jd_joy.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:745:27)
>   at Module.require (internal/modules/cjs/loader.js:961:19)
>   at require (internal/modules/cjs/helpers.js:92:18)
>   at Object. (/ql/scripts/asd920_Auto-jd_jd_joy.js:29:18)
>   at Module._compile (internal/modules/cjs/loader.js:1072:14)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>   at Module.load (internal/modules/cjs/loader.js:937:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/ql/scripts/asd920_Auto-jd_jd_joy.js' ]
>   }
> 
> ## 执行结束... 2021-08-28 08:19:20 耗时 0 秒

没拉取到那个js文件

**Comment by dafeida** [comment]
> > ## 开始执行... 2021-08-28 08:19:20
> > 🔔宠汪汪, 开始!
> > internal/modules/cjs/loader.js:892
> > throw err;
> > ^
> > Error: Cannot find module './JDJRValidator_Pure'
> > Require stack:
> > 
> > * /ql/scripts/asd920_Auto-jd_jd_joy.js
> >   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
> >   at Function.Module._load (internal/modules/cjs/loader.js:745:27)
> >   at Module.require (internal/modules/cjs/loader.js:961:19)
> >   at require (internal/modules/cjs/helpers.js:92:18)
> >   at Object. (/ql/scripts/asd920_Auto-jd_jd_joy.js:29:18)
> >   at Module._compile (internal/modules/cjs/loader.js:1072:14)
> >   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
> >   at Module.load (internal/modules/cjs/loader.js:937:32)
> >   at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> >   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [ '/ql/scripts/asd920_Auto-jd_jd_joy.js' ]
> >   }
> > 
> > ## 执行结束... 2021-08-28 08:19:20 耗时 0 秒
> 
> 没拉取到那个js文件

1、如何操作设置解决这个问题呢？重新执行一下添加任务脚本吗？
2、cash.js也有一个问题“
"Response code 403 (Forbidden)"
签到领现金 getSign API请求失败，请检查网路重试
两个多个账号，其中一个账号出现这个提示，其他的正常。

**Comment by asd920** [comment]
你是用青龙的？ 拉库命令   ql repo https://github.com/asd920/Auto-jd.git "jd_|jx_|getJDCookie" "backUp" "^jd[^_]|USER|sendNotify|sign_graphics_validate|JDJR"    重新添加下吧
