### ISSUE TITLE
拉取脚本不成功,一直提示检查网络

### ISSUE THREAD

**Issue by wpy0032** [asd920/Auto-jd#48]
![image](https://user-images.githubusercontent.com/30211666/131451258-7af25e2b-6a3e-424d-8be5-10b4b569654a.png)
服务器上试了下,是可以ping通github的,但一直失败,是什么原因呢

**Comment by asd920** [comment]
你试试直接在服务器上拉，一般都是网络原因造成的

**Comment by yumengbdw** [comment]
昨天开始github上配置的，都一直拉不成功
![image](https://user-images.githubusercontent.com/11400046/133016834-12c39638-f255-498f-bb68-0a518a3339ad.png)
