### ISSUE TITLE
getJDCookie.js

### ISSUE THREAD

**Issue by cy920820** [asd920/Auto-jd#53]
运行之后直接报错：扫描登录失败:其他未知状态异常：{"check_ip":0,"errcode":8,"message":"您的账号存在风险，请您稍后再试或联系客服"}

**Comment by cy920820** [comment]
求解，感谢

**Comment by asd920** [comment]
> 求解，感谢

扫码登陆不行的，需要直接抓

**Comment by cy920820** [comment]
直接抓的话，ck一天就过期了，请问一下这是为什么呢？
