### ISSUE TITLE
请教一下青龙v2.10.0添加cookie是直接在环境变量里新建JD_COOKIE变量，还是需要修改jdCookie.js文件？

### ISSUE THREAD

**Issue by hzx8848** [asd920/Auto-jd#60]
我之前在脚本管理里边修改jdCookie.js，但是好像会被定时任务里的定时拉取仓库命令覆盖掉

**Comment by asd920** [comment]
> 我之前在脚本管理里边修改jdCookie.js，但是好像会被定时任务里的定时拉取仓库命令覆盖掉

新建JD_COOKIE变量

**Comment by hzx8848** [comment]
感谢大佬！通知的话需要修改notify.py文件吗，还是直接在面板的通知设置里填就行？

**Comment by asd920** [comment]
在面板的通知设置里填

**Comment by hzx8848** [comment]
明白了，感谢！
