### ISSUE TITLE
京东签到总是显示已签到，但实际上并没有签到

### ISSUE THREAD

**Issue by wpl455209682** [asd920/Auto-jd#61]
2021-11-05T00:00:14.282Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 去做【每日签到领京豆】

2021-11-05T00:00:14.694Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 今日已签到

2021-11-05T00:00:19.261Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 去做【逛短视频会场，赢京豆】

2021-11-05T00:00:19.261Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 任务已完成

**Comment by asd920** [comment]
> 2021-11-05T00:00:14.282Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 去做【每日签到领京豆】
> 
> 2021-11-05T00:00:14.694Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 今日已签到
> 
> 2021-11-05T00:00:19.261Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 去做【逛短视频会场，赢京豆】
> 
> 2021-11-05T00:00:19.261Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 任务已完成

哪个脚本

**Comment by wpl455209682** [comment]
jd_bean_sign.js

**Comment by wpl455209682** [comment]
> > 2021-11-05T00:00:14.282Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 去做【每日签到领京豆】
> > 2021-11-05T00:00:14.694Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 今日已签到
> > 2021-11-05T00:00:19.261Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 去做【逛短视频会场，赢京豆】
> > 2021-11-05T00:00:19.261Z d94dba8c-3a5e-4c1f-8d12-89c0131e3b0d 任务已完成
> 
> 哪个脚本

jd_bean_sign.js
