### ISSUE TITLE
京东价保，可以出一个脚本么？

### ISSUE THREAD

**Issue by wenwenGeek** [asd920/Auto-jd#63]

**Comment by asd920** [comment]
脚本里有

**Comment by wenwenGeek** [comment]
![image](https://user-images.githubusercontent.com/11352709/141770977-1390ebcb-70da-47dd-97ee-fcc383c54b16.png)

**Comment by wenwenGeek** [comment]
> 脚本里有

抛异常了， 这个怎么处理？
