### ISSUE TITLE
脚本重复问题

### ISSUE THREAD

**Issue by phoenixxie0** [asd920/Auto-jd#68]
jd_joypark_joy.js和jd_joy_park_task.js 以及 jd_cash_exchange.js和jd_car_exchange.js
是相同的

**Comment by asd920** [comment]
> jd_joypark_joy.js和jd_joy_park_task.js 以及 jd_cash_exchange.js和jd_car_exchange.js 是相同的

已删除重复脚本，谢谢提醒！

**Comment by phoenixxie0** [comment]
Thx
