### ISSUE TITLE
JD_DailyBonus.js 文件不存在

### ISSUE THREAD

**Issue by linyongfu2013** [asd920/Auto-jd#69]
京东多合一签到报错脚本文件不存在，检查青龙脚本里确实没有，使用命令单独拉取该脚本也失败

```
ubuntu@VM-20-9-ubuntu:~/ql$ docker exec -it qinglong ql raw https://ghproxy.com/https://raw.githubusercontent.com/asd920/Auto-jd/main/Me/JD_DailyBonus.js
## 开始执行... 2021-11-23 15:36:31

--------------------------------------------------------------

开始下载：https://ghproxy.com/https://raw.githubusercontent.com/asd920/Auto-jd/main/Me/JD_DailyBonus.js 

保存路径：/ql/raw/Me_JD_DailyBonus.js

下载 Me_JD_DailyBonus.js 失败，保留之前正常下载的版本...
```

**Comment by asd920** [comment]
> 京东多合一签到报错脚本文件不存在，检查青龙脚本里确实没有，使用命令单独拉取该脚本也失败
> 
> ```
> ubuntu@VM-20-9-ubuntu:~/ql$ docker exec -it qinglong ql raw https://ghproxy.com/https://raw.githubusercontent.com/asd920/Auto-jd/main/Me/JD_DailyBonus.js
> ## 开始执行... 2021-11-23 15:36:31
> 
> --------------------------------------------------------------
> 
> 开始下载：https://ghproxy.com/https://raw.githubusercontent.com/asd920/Auto-jd/main/Me/JD_DailyBonus.js 
> 
> 保存路径：/ql/raw/Me_JD_DailyBonus.js
> 
> 下载 Me_JD_DailyBonus.js 失败，保留之前正常下载的版本...
> ```

加上拉取JD_DailyBonus.js了

**Comment by linyongfu2013** [comment]
辛苦了，我在面板上手工创建脚本了
