### ISSUE TITLE
老版本同步代码一直不成功

### ISSUE THREAD

**Issue by yumengbdw** [asd920/Auto-jd#74]
![image](https://user-images.githubusercontent.com/11400046/148714715-d51c4ac9-a62b-4242-9eb5-de6a9f87f17d.png)

**Comment by yumengbdw** [comment]
大概两三周前都是正常

**Comment by asd920** [comment]
> Author

报错原因发出来

**Comment by yumengbdw** [comment]
应该是权限过期了🤦‍♀️   Authentication failed
