### ISSUE TITLE
您好，请问elecV2P模式下，京东cookie在哪里维护

### ISSUE THREAD

**Issue by RuiTeemoZhang** [asd920/Auto-jd#77]
cookiesArr = [$.getdata('CookieJD'), $.getdata('CookieJD2'), ...jsonParse($.getdata('CookiesJD') || "[]").map(item => item.cookie)].filter(item => !!item);

请问这句话 $.getdata('CookieJD')  的CookieJD  是我手动往里面填写吗

盼回复 感谢

**Comment by asd920** [comment]
> cookiesArr = [$.getdata('CookieJD'), $.getdata('CookieJD2'), ...jsonParse($.getdata('CookiesJD') || "[]").map(item => item.cookie)].filter(item => !!item);
> 
> 请问这句话 $.getdata('CookieJD') 的CookieJD 是我手动往里面填写吗
> 
> 盼回复 感谢

https://github.com/asd920/Auto-jd/blob/main/backUp/elecV2P.md  通知里有说明。

**Comment by RuiTeemoZhang** [comment]
> > cookiesArr = [$.getdata('CookieJD'), $.getdata('CookieJD2'), ...jsonParse($.getdata('CookiesJD') || "[]").map(item => item.cookie)].filter(item => !!item);
> > 请问这句话 $.getdata('CookieJD') 的CookieJD 是我手动往里面填写吗
> > 盼回复 感谢
> 
> https://github.com/asd920/Auto-jd/blob/main/backUp/elecV2P.md 通知里有说明。

您好 ，我按照这个填写，然后点保存当前cookie 也提示成功

可是 执行js 的时候报错 
![image](https://user-images.githubusercontent.com/95168452/149090661-3b258bdf-5724-43f8-98d0-93f182ee6236.png)

**Comment by asd920** [comment]
> > > cookiesArr = [$.getdata('CookieJD'), $.getdata('CookieJD2'), ...jsonParse($.getdata('CookiesJD') || "[]").map(item => item.cookie)].filter(item => !!item);
> > > 请问这句话 $.getdata('CookieJD') 的CookieJD 是我手动往里面填写吗
> > > 盼回复 感谢
> > 
> > 
> > https://github.com/asd920/Auto-jd/blob/main/backUp/elecV2P.md 通知里有说明。
> 
> 您好 ，我按照这个填写，然后点保存当前cookie 也提示成功
> 
> 可是 执行js 的时候报错 ![image](https://user-images.githubusercontent.com/95168452/149090661-3b258bdf-5724-43f8-98d0-93f182ee6236.png)

用elecv2p来跑有些脚本会不兼容，你试试把报错的代码删了试试。

**Comment by RuiTeemoZhang** [comment]
> cookiesArr = [$.getdata('CookieJD'), $.getdata('CookieJD2'), ...jsonParse($.getdata('CookiesJD') || "[]").map(item => item.cookie)].filter(item => !!item);

报错的代码 就是这句话  cookiesArr = [$.getdata('CookieJD'), $.getdata('CookieJD2'), ...jsonParse($.getdata('CookiesJD') || "[]").map(item => item.cookie)].filter(item => !!item);

感觉他是没有获取到 京东cookie
