### ISSUE TITLE
您好，请问 特物Z 的任务 报 获取活动详情失败

### ISSUE THREAD

**Issue by RuiTeemoZhang** [asd920/Auto-jd#78]
如题，执行任务 报 获取活动详情失败
PS,, task.json 的 特物Z  "time": "**cron** 23 8,9 * * *", 是不是要改成 "time": "23 8,9 * * *",  哈

盼回复，感谢

**Comment by asd920** [comment]
> 如题，执行任务 报 获取活动详情失败 PS,, task.json 的 特物Z "time": "**cron** 23 8,9 * * *", 是不是要改成 "time": "23 8,9 * * *", 哈
> 
> 盼回复，感谢

是的，我已更改。

**Comment by RuiTeemoZhang** [comment]
> > 如题，执行任务 报 获取活动详情失败 PS,, task.json 的 特物Z "time": "**cron** 23 8,9 * * *", 是不是要改成 "time": "23 8,9 * * *", 哈
> > 盼回复，感谢
> 
> 是的，我已更改。

请问 特物Z 的js 也更改了吗哈
