### ISSUE TITLE
您好  jd_ms.js 报 入参异常

### ISSUE THREAD

**Issue by RuiTeemoZhang** [asd920/Auto-jd#79]

**Comment by RuiTeemoZhang** [comment]
您好，现在报错 入参异常
![image](https://user-images.githubusercontent.com/95168452/149702552-ef0b0c45-92f8-4d5b-ba32-ef1a89712b07.png)

**Comment by asd920** [comment]
> 您好，现在报错 入参异常 ![image](https://user-images.githubusercontent.com/95168452/149702552-ef0b0c45-92f8-4d5b-ba32-ef1a89712b07.png)

秒秒币18日就清零了，就不维护了

**Comment by RuiTeemoZhang** [comment]
> > 您好，现在报错 入参异常 ![image](https://user-images.githubusercontent.com/95168452/149702552-ef0b0c45-92f8-4d5b-ba32-ef1a89712b07.png)
> 
> 秒秒币18日就清零了，就不维护了

好滴 感谢回复
